from controllers.edit_name_controller import EditNameController
from controllers.highscores_controller import HighscoresController
from controllers.logo_controller import LogoController
from controllers.menu_controller import MenuController
from controllers.play_controller import PlayController
from controllers.win_controller import WinController
